"""
Django settings for PerfumeValley project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path


SHIPROCKET_EMAIL="anu525495@gmail.com"
SHIPROCKET_PASSWORD="tiYTExSq1C9o$EJ@"
# Celery Settings
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_IMPORTS = ('admin_panel.tasks', 'user_panel.tasks')

VAPID_PUBLIC_KEY = "BOq9RSStBKaio0QslQFxOpu3IYUrIiypkGLTOIIWw4-pAiE-BQfLreFmd2EmkBdvAnDrKP8LYSHhJVP7n83MLmo"
VAPID_PRIVATE_KEY = "sw-kz4Rgf5IcgrM76a9ZWstlBZz74xYT9u-S8ARTFgM"
VAPID_ADMIN_EMAIL = "mailto:admin@example.com"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a9qr^u367(eb+12ux$#5s5_zoo9#2ed1u7ovde$($nn(bgfodd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# settings.py


ALLOWED_HOSTS = ["*"]

X_FRAME_OPTIONS = 'ALLOWALL'

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000, public',
}

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "admin_panel",
    "user_panel",
    "django_celery_beat",
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
    'compressor',
]


STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- Add this here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_panel.middleware.BlockedUserMiddleware',  
]



ROOT_URLCONF = 'PerfumeValley.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global Templates Folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'user_panel.context_processors.category_subcategory_navbar', #add this line
                'user_panel.context_processors.festival_offer_context',
                'user_panel.context_processors.latest_purchases_orders',
                'user_panel.context_processors.wishlist_count',  # ← Add this line
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_panel.context_processors.admin_context',  # ← Add this line
                  # ← Add this line

            ],
        },
    },
]


WSGI_APPLICATION = 'PerfumeValley.wsgi.application'
ASGI_APPLICATION = 'PerfumeValley.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],  # Redis container name
            "capacity": 1500,           # Max messages per channel
            "expiry": 60,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Use PostgreSQL backend
        'NAME': 'PerfumeValley',  # Replace with your database name
        'USER':'admin',  # Replace with your database user
        'PASSWORD': 'Perfumevalley12345',  # Replace with your database password
        'HOST': 'database-2.cr4y64o0iohu.eu-north-1.rds.amazonaws.com',  # Set to 'localhost' or the IP address of your PostgreSQL server
        'PORT': '3306',  # Default PostgreSQL port
        'OPTIONS': {
             'ssl': {'ssl-ca': ''},  # Disable SSL
             'init_command': 'SET sql_mode="STRICT_TRANS_TABLES";',
          },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
CSRF_TRUSTED_ORIGINS = [
    "https://perfumevalleyworld.com",
    "https://www.perfumevalleyworld.com",
    
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

import os
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# # Optional: during development



# -----------------------------
# STATIC FILES + COMPRESSOR SETTINGS
# -----------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Django Compressor
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_STORAGE = STATICFILES_STORAGE

# Compress CSS & JS
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',  # Minify CSS
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',  # Minify JS
]

# WhiteNoise settings for serving static files
WHITENOISE_USE_FINDERS = True
WHITENOISE_MAX_AGE = 31536000


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# settings.py

# S3 Storage settings
AWS_STORAGE_BUCKET_NAME = 'perfumevalleyworld'
AWS_S3_REGION_NAME = 'eu-north-1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
#AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True
AWS_QUERYSTRING_AUTH = False
# Build the custom domain URL for media
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

# Tell Django to use S3 for media files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

LOGIN_URL = '/login/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RAZORPAY_KEY_ID='rzp_live_Rl8KKKylmcJZ6y'
RAZORPAY_SECRET='YAoy1Cg8Po2p61HUmRom2x95'

# settings.py
APPEND_SLASH = False
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'perfumevalleyworld5@gmail.com'
EMAIL_HOST_PASSWORD = 'lnkxzddnqycdkjxw'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# Redis Settings
REDIS_HOST = 'redis'
REDIS_PORT = 6379
REDIS_DB = 0
